export const strings = {
  siteTitle: "Laboratório de Tesouraria",
  siteSubtitle: "Prof. José Américo",
  heroTitle: "Laboratório de Tesouraria de Empresas",
  heroPitch:
    "Simulações interativas para o aprendizado prático da gestão de tesouraria — capital de giro, caixa, estoques, recebíveis e fornecedores.",
  professor: "Prof. José Américo",
  institution: "COPPEAD / UFRJ — MBA",
  modulesTitle: "Módulos do curso",
  backHome: "← Início",
  backHub: "← Voltar aos cenários",
  prevStep: "← Etapa anterior",
  score: "Pontuação",
  context: "Contexto",
  keyFacts: "Dados-chave",
  statements: "Demonstrações financeiras",
  correct: "✓ Correto",
  canImprove: "✗ Pode melhorar",
  prevAnswer: "Resposta anterior",
  currentAnswer: "resposta atual",
  keepOrChange: "— você pode manter ou escolher outra opção.",
  chooseBranch: "Escolha sua decisão",
  branchPick: "Encruzilhada",
  branchInstructions:
    "Cada caminho leva a um resultado diferente. Avalie os trade-offs e escolha sua linha de ação.",
  result: "Resultado",
  resultIntro: "Veja o impacto da sua decisão:",
  reflection: "Reflexão",
  reflectionIntro: "Para fechar — uma pergunta sobre o que aconteceu:",
  finishReturn: "Finalizar e voltar →",
  tryAnother: "Tentar outro cenário",
  concluido: "Concluído",
  emBreve: "Em breve",
  objetivosAprendizagem: "Objetivos de aprendizagem",
  difficulty: "Dificuldade",
  estimatedMinutes: "min",
  scenariosTitle: "Cenários",
  startScenario: "Iniciar cenário",
  complete: "Cenário concluído",
  completeIntro: "Você concluiu o cenário. Veja seu desempenho:",
  finalScore: "Pontuação final",
  footer: "Laboratório de Tesouraria de Empresas — Prof. José Américo · COPPEAD / UFRJ",
  navHome: "Início",
  navM1: "Capital de Giro",
  navM2: "Orçamento de Caixa",
  navM3: "Estoques",
  navM4: "Contas a Receber",
  navM5: "Fornecedores",
  navContato: "Contato",
  methodologyTitle: "Metodologia de Aprendizado",
  methodStep1Title: "1. Seleção do Módulo",
  methodStep1Text: "Escolha entre os 5 módulos da gestão de tesouraria de empresas.",
  methodStep2Title: "2. Análise de Cenários",
  methodStep2Text: "Tome decisões em encruzilhadas reais, com etapas, branches e reflexão final.",
  methodStep3Title: "3. Validação Técnica",
  methodStep3Text: "Avalie impactos financeiros, ganhe pontuação e consolide rigor analítico.",
  progressLabel: "Progresso",
  concluidos: "concluídos",
  modulesAccessTitle: "Acesse os módulos clicando abaixo",
  footerCopyright1: "© 2026 Laboratório de Tesouraria de Empresas. Todos os direitos reservados.",
  footerCopyright2: "Prof. José Américo · FGV",
  footerContact: "Dúvidas, Sugestões: Entre em contato",
  contactTitle: "Entre em Contato",
  contactSubtitle: "Envie suas dúvidas, sugestões ou feedback sobre o Laboratório de Tesouraria.",
  contactName: "Nome (opcional)",
  contactNamePlaceholder: "Seu nome",
  contactEmail: "E-mail (opcional)",
  contactEmailPlaceholder: "seu@email.com",
  contactMessage: "Mensagem",
  contactMessagePlaceholder: "Escreva sua mensagem aqui...",
  contactSubmit: "Enviar Mensagem",
  contactSending: "Enviando...",
  contactSent: "Mensagem enviada com sucesso!",
  contactError: "Falha ao enviar. Tente novamente em instantes.",
  backToModules: "Voltar",
} as const;
