export const strings = {
  siteTitle: "Laboratório de Tesouraria",
  siteSubtitle: "Prof. José Américo",
  heroTitle: "Laboratório de Tesouraria de Empresas",
  heroPitch:
    "Simulações interativas para o aprendizado prático da gestão de tesouraria — capital de giro, caixa, estoques, recebíveis e fornecedores.",
  professor: "Prof. José Américo",
  institution: "COPPEAD / UFRJ — MBA",
  modulesTitle: "Módulos do curso",
  backHome: "← Início",
  backHub: "← Voltar aos cenários",
  prevStep: "← Etapa anterior",
  score: "Pontuação",
  context: "Contexto",
  keyFacts: "Dados-chave",
  statements: "Demonstrações financeiras",
  correct: "✓ Correto",
  canImprove: "✗ Pode melhorar",
  prevAnswer: "Resposta anterior",
  currentAnswer: "resposta atual",
  keepOrChange: "— você pode manter ou escolher outra opção.",
  chooseBranch: "Escolha sua decisão",
  branchPick: "Encruzilhada",
  branchInstructions:
    "Cada caminho leva a um resultado diferente. Avalie os trade-offs e escolha sua linha de ação.",
  result: "Resultado",
  resultIntro: "Veja o impacto da sua decisão:",
  reflection: "Reflexão",
  reflectionIntro: "Para fechar — uma pergunta sobre o que aconteceu:",
  finishReturn: "Finalizar e voltar →",
  tryAnother: "Tentar outro cenário",
  concluido: "Concluído",
  emBreve: "Em breve",
  objetivosAprendizagem: "Objetivos de aprendizagem",
  difficulty: "Dificuldade",
  estimatedMinutes: "min",
  scenariosTitle: "Cenários",
  startScenario: "Iniciar cenário",
  complete: "Cenário concluído",
  completeIntro: "Você concluiu o cenário. Veja seu desempenho:",
  finalScore: "Pontuação final",
  footer: "Laboratório de Tesouraria de Empresas — Prof. José Américo · COPPEAD / UFRJ",
} as const;
